spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dragon?useSSL=false&serverTimezone=UTC
    username: dragon
    password: 2428
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
      hibernate:
          ddl-auto: create
      show-sql: true
      properties:
          hibernate:
              format_sql: true